"""Builder tests: all combinations, edge-case inputs, and protections."""

# ----- IMPORTS & CONFIGURATION ---------------------------------------------- #

import itertools
import re
import sys
import tempfile
import unittest
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import build
from errors import BuildError
from layout import SCREENS, SIDES, TYPES, compute

# ----- TEST SUITE ----------------------------------------------------------- #


class BuildTest(unittest.TestCase):
    def setUp(self):
        """Create a temporary workspace directory and register cleanup."""
        self.tmp = Path(tempfile.mkdtemp())
        self.addCleanup(lambda: __import__("shutil").rmtree(self.tmp, ignore_errors=True))

    def photo(self, name, size=(1600, 1200), mode="RGB", color=(120, 80, 60)):
        """Generate a dummy test image file with specified dimensions, mode, and color."""
        path = self.tmp / name
        Image.new(mode, size, color if mode == "RGB" else color + (128,)).save(path)
        return str(path)

    def test_every_combination_builds_and_is_native(self):
        """Verify that all 32 resolution, style, and side combinations build native-resolution backgrounds."""
        photo = self.photo("p.jpg")
        for screen, style, side in itertools.product(SCREENS, TYPES, SIDES):
            with self.subTest(screen=screen, style=style, side=side):
                out = self.tmp / f"{screen}-{style}-{side}"
                build.build(out, screen, style, side, photo, "cachyos", "soft")
                with Image.open(out / "background.jpg") as bg:
                    self.assertEqual(bg.size, SCREENS[screen][:2])

    def test_layout_stays_inside_screen_and_apart(self):
        """Verify that layout rectangles (photo and menu) fit within screen bounds without colliding."""
        for screen, style, side in itertools.product(SCREENS, TYPES, SIDES):
            lay = compute(screen, style, side)
            w, h = lay["size"]
            for rect in (lay["photo"], lay["menu"]):
                x, y, rw, rh = rect
                self.assertTrue(
                    0 <= x and 0 <= y and x + rw <= w and y + rh <= h, (screen, style, side, rect)
                )

    def test_theme_txt_percentages_in_range(self):
        """Verify that all percentage values in theme.txt stay between 0% and 100%."""
        out = self.tmp / "t"
        build.build(out, "1600p", "window", "right", self.photo("p.jpg"), "cachyos", "none")
        for value in re.findall(r"= (\d+\.\d+)%", (out / "theme.txt").read_text()):
            self.assertTrue(0 <= float(value) <= 100, value)

    def test_odd_inputs_are_accepted(self):
        """Verify that odd image formats (alpha channel, tiny sizes, portrait orientation) are handled safely."""
        cases = {
            "alpha.png": dict(mode="RGBA"),
            "tiny.jpg": dict(size=(64, 48)),
            "portrait.jpg": dict(size=(600, 1800)),
        }
        for name, kw in cases.items():
            with self.subTest(name=name):
                build.build(
                    self.tmp / name.split(".")[0],
                    "1080p",
                    "window",
                    "left",
                    self.photo(name, **kw),
                    "none",
                    "soft",
                )

    def test_corrupt_photo_is_a_clean_error(self):
        """Verify that corrupt or unreadable image files raise a clean BuildError without side effects."""
        bad = self.tmp / "bad.jpg"
        bad.write_bytes(b"not an image")
        with self.assertRaises(BuildError):
            build.build(self.tmp / "t", "1080p", "window", "left", str(bad), "none", "soft")
        self.assertFalse((self.tmp / "t").exists())

    def test_names_cannot_escape_asset_directories(self):
        """Verify that path traversal attempts in photo or logo names are rejected."""
        for bad in ("../x", "a/b", ".hidden", ""):
            with self.assertRaises(BuildError):
                build.find_asset(ROOT / "backgrounds", bad, (".jpg",), "photo")
        with self.assertRaises(BuildError):
            build.build(
                self.tmp / "t",
                "1080p",
                "window",
                "left",
                self.photo("p.jpg"),
                "../../etc/passwd",
                "soft",
            )

    def test_foreign_directory_is_never_replaced(self):
        """Verify that directories not generated by this theme builder are never overwritten or deleted."""
        foreign = self.tmp / "foreign"
        foreign.mkdir()
        (foreign / "keep").write_text("x")
        with self.assertRaises(BuildError):
            build.build(foreign, "1080p", "window", "left", self.photo("p.jpg"), "none", "soft")
        self.assertTrue((foreign / "keep").exists())
        self.assertEqual([p.name for p in self.tmp.iterdir() if p.name.startswith(".foreign")], [])

    def test_rebuild_replaces_own_directory(self):
        """Verify that subsequent builds over an existing theme directory replace it cleanly."""
        out = self.tmp / "t"
        build.build(out, "1080p", "window", "left", self.photo("p.jpg"), "none", "soft")
        build.build(out, "1600p", "sharp", "left", self.photo("p.jpg"), "none", "soft")
        with Image.open(out / "background.jpg") as bg:
            self.assertEqual(bg.size, (2560, 1600))


# ----- TEST RUNNER ---------------------------------------------------------- #

if __name__ == "__main__":
    unittest.main()
