"""Theme geometry by resolution, style, and side. All rectangles are (x, y, w, h) in pixels."""

from typing import TypedDict

from palette import PALETTE

# ----- THEME SPECIFICATIONS & PRESETS --------------------------------------- #

SCREENS = {  # name: (width, height, Unifont font size)
    "1080p": (1920, 1080, 16),
    "1440p": (2560, 1440, 24),
    "1600p": (2560, 1600, 24),
    "4k": (3840, 2160, 32),
}
FONTS = {  # font: item height, icon, icon-text space, padding, spacing
    16: (48, 32, 6, 3, 6),
    24: (72, 48, 8, 4, 8),
    32: (96, 64, 12, 6, 12),
}
TYPES = ("window", "float", "sharp", "blur")
SIDES = ("left", "right")

Size = tuple[int, int]
Rect = tuple[int, int, int, int]


class Layout(TypedDict):
    size: Size
    font: int
    u: float
    card: Rect
    photo: Rect
    menu: Rect
    logo: int
    card_radius: int
    photo_radius: int


# ----- GEOMETRY COMPUTATION ------------------------------------------------- #


def compute(screen: str, style: str, side: str) -> Layout:
    """Compute card, photo, menu, and logo; geometry scales with height (1080 = 1x)."""
    w, h, font = SCREENS[screen]
    u = h / 1080
    if style == "window":
        cw = min(round(1180 * u), round(0.82 * w))
        ch = round(640 * u)
        card = ((w - cw) // 2, (h - ch) // 2, cw, ch)
    else:
        card = (0, 0, w, h)
    cx, cy, cw, ch = card
    pad = round((14 if style == "window" else 24 if style == "float" else 0) * u)
    pw = round(0.42 * cw)
    photo = (cx + pad, cy + pad, pw - pad, ch - 2 * pad)
    free = cw - pw - round(80 * u)  # space for menu next to photo
    mw = min(free, round(660 * u))
    menu = (cx + pw + round(36 * u) + (free - mw) // 2, cy + round(0.16 * ch), mw, round(0.62 * ch))
    logo = round(min(photo[2], photo[3]) * 0.26)
    if side == "right":  # mirror photo/menu order within the card
        photo = (cx + cw - (photo[0] - cx) - photo[2],) + photo[1:]
        menu = (cx + cw - (menu[0] - cx) - menu[2],) + menu[1:]
    return {
        "size": (w, h),
        "font": font,
        "u": u,
        "card": card,
        "photo": photo,
        "menu": menu,
        "logo": logo,
        "card_radius": round(22 * u) if style == "window" else 0,
        "photo_radius": round(14 * u) if style in ("window", "float") else 0,
    }


# ----- GRUB THEME CONFIGURATION GENERATOR ----------------------------------- #


def theme_txt(lay: Layout) -> str:
    """Generate theme.txt: percentage positions so they handle GRUB fallback to a different video mode."""
    w, h = lay["size"]
    item_h, icon, space, pad, spacing = FONTS[lay["font"]]
    font = f'Unifont Regular {lay["font"]}'
    px, py, pw, ph = lay["photo"]
    mx, my, mw, mh = lay["menu"]
    pct = lambda v, tot: f"{v * 100 / tot:.2f}%"
    ls = lay["logo"]
    return f"""# Tokyo Night for GRUB, generated by tools/build.py
desktop-image: "background.jpg"
desktop-color: "{PALETTE["bg_dark"]}"
title-text: ""
terminal-font: "Terminus Regular {18 if lay["font"] > 16 else 14}"
terminal-left: "0"
terminal-top: "0"
terminal-width: "100%"
terminal-height: "100%"
terminal-border: "0"

+ boot_menu {{
  left = {pct(mx, w)}
  top = {pct(my, h)}
  width = {pct(mw, w)}
  height = {pct(mh, h)}
  item_font = "{font}"
  item_color = "{PALETTE["fg_dark"]}"
  selected_item_color = "{PALETTE["fg"]}"
  icon_width = {icon}
  icon_height = {icon}
  item_icon_space = {space}
  item_height = {item_h}
  item_padding = {pad}
  item_spacing = {spacing}
  selected_item_pixmap_style = "select_*.png"
}}

+ image {{
  left = {pct(px + (pw - ls) // 2, w)}
  top = {pct(py + round(0.40 * ph) - ls // 2, h)}
  file = "logo.png"
}}

+ label {{
  left = {pct(px, w)}
  top = {pct(py + ph - round(64 * lay["u"]), h)}
  width = {pct(pw, w)}
  align = "center"
  text = "e  edit      c  console"
  color = "{PALETTE["fg_dark"]}"
  font = "{font}"
}}

+ label {{
  left = {pct(mx, w)}
  top = {pct(my + mh + round(16 * lay["u"]), h)}
  width = {pct(mw, w)}
  align = "center"
  id = "__timeout__"
  text = "Booting in %d seconds"
  color = "{PALETTE["comment"]}"
  font = "{font}"
}}
"""
